// src/app/layout.js (for Next.js App Router)

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from '@/components/navbar/Navbar';
import Sidebar from '@/components/sidebar/Sidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
      <div className="flex">
      
      <Sidebar/>
      

      <div className="w-screen">     <Navbar/>
          <div className="bg-slate-300  dark:bg-black dark:text-white mt-2 w-[98%] ml-4 h-[86%] " >{children} 
             </div> 
             
              </div>
      
         </div>
      
       
      
      </body>
    </html>
  );
}
